#!/usr/bin/expect -f

set force_conservative 0; # set to 1 to force conservative mode even if script wasn't run conservatively originally

if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set cmd [lindex $argv 0];
set password [lindex $argv 1];

set timeout -1
spawn -noecho {*}$cmd
match_max 100000
expect "Password: "
send "$password\r"
expect eof
