alias aptAutoremove='sudo apt-get autoremove'
alias aptClean='sudo apt-get clean'
alias aptInstall='sudo apt-get install'
alias aptPurge='sudo apt-get purge'
alias aptRemove='sudo apt-get remove'
alias aptUpdate='sudo apt-get update'
alias aptUpgrade='sudo apt-get upgrade'
